name: SonarCloud Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=YogeshBhosale1999_java-reachability-playground
            -Dsonar.organization=YogeshBhosale1999
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
